[package]
name = "gvm-rs"
version = "0.1.0"
edition = "2024"
authors = ["Björn Ricks <bjoern.ricks@gmail.com>"]
description = "A Rust library for connecting to the Greenbone Vulnerability Management API."
license = "GPL-3.0-or-later"

[[bin]]
name = "gvm-cli"
path = "src/cli/main.rs"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
quick-xml = { version = "0.39.2", features = ["serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_with = "3.20.0"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.1", features = ["serde"] }
