[package]
name = "gvm-rs"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[workspace]
members = ["gvm-rs-derive"]

[workspace.package]
authors = ["Björn Ricks <bjoern.ricks@gmail.com>"]
description = "A Rust library for connecting to the Greenbone Vulnerability Management API."
edition = "2024"
license = "GPL-3.0-or-later"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "gvm-cli"
path = "src/cli/main.rs"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
quick-xml = { version = "0.41.0", features = ["serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_with = "3.18.0"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.1", features = ["serde"] }
gvm-rs-derive = { path = "./gvm-rs-derive" }
